### ISSUE TITLE
Transfer repo to me

### ISSUE THREAD

**Issue by davelab6** [googlefonts/questrial#2]
Please transfer the repo to me, so I can move it to the https://github.com/googlefonts org :)

**Comment by graphicore** [comment]
It says to me:

>  You don’t have the permission to create public repositories on googlefonts

**Comment by graphicore** [comment]
> repo to me

I think I misread this. Understood, requested!

**Comment by davelab6** [comment]
> Oops! That repository transfer has expired.

Please do againi :)
